In [6]:
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix


In [9]:
#import the data in df
df=pd.read_excel("data123.xlsx")

In [10]:
df.head()

School  Student Enrolments  Teaching Staff  \
0   Ballarat Clarendon College                1422             163   
1             Emmanuel College                2070             152   
2  Doncaster secondary college                1494             114   
3           St Kevin's College                2099             228   
4     Canley Vale High School                 1574             105   

   ICSEA_Score  Expenditure   Fund_req  
0         1160         15176         1  
1         1059         11876         0  
2         1061         15476         1  
3         1177         12446         0  
4          952         16176         1

In [17]:
X = df.iloc[:, 1:-1].values
y = df.iloc[:, -1].values

In [18]:
X

array([[ 1422,   163,  1160, 15176],
       [ 2070,   152,  1059, 11876],
       [ 1494,   114,  1061, 15476],
       [ 2099,   228,  1177, 12446],
       [ 1574,   105,   952, 16176],
       [ 1204,    94,  1076, 16876],
       [  722,    59,   931, 16186],
       [  705,    57,  1012, 15176],
       [ 1168,    97,   941, 15176],
       [  539,    45,   853, 10176],
       [  897,    72,   968, 12176],
       [ 1113,    80,   968, 15176],
       [ 1644,   117,  1041, 15176],
       [  842,    73,  1068, 10886],
       [ 1883,   192,  1116, 15176],
       [ 1217,   118,  1115, 15176],
       [ 1457,   113,  1050, 16176],
       [ 1331,   107,  1069, 16776],
       [  891,    84,   982, 14176],
       [  973,    80,  1012, 18176],
       [  946,    66,  1067, 17176],
       [  235,    23,  1030, 12176],
       [  171,    24,   992, 11176],
       [  132,    16,   945, 12276],
       [  767,    69,   951, 16676],
       [ 1424,   132,  1021, 17176],
       [  535,    45,   945, 18176],
 

In [19]:
y

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0], dtype=int64)

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)

In [37]:
#modelling
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 5, criterion = 'entropy')
model.fit(X_train, y_train)


RandomForestClassifier(criterion='entropy', n_estimators=5)

In [38]:
#predicting results on test set
y_pred = model.predict(X_test)


In [39]:
X_test

array([[  235,    23,  1030, 12176],
       [  891,    84,   982, 14176],
       [ 2099,   228,  1177, 12446],
       [  842,    73,  1068, 10886],
       [  171,    24,   992, 11176],
       [  132,    16,   945, 12276],
       [  722,    59,   931, 16186],
       [  709,    68,  1090, 15176],
       [ 1644,   117,  1041, 15176],
       [  535,    45,   945, 18176]], dtype=int64)

In [40]:
y_pred

array([0, 1, 0, 0, 0, 0, 1, 1, 1, 1], dtype=int64)

In [41]:
confusion_matrix(y_true=y_test, y_pred=y_pred)


array([[4, 1],
       [1, 4]], dtype=int64)

In [49]:
#0 means fund required, 1 means fund no required
unseenXExpand=[]
unseenXExpand.append([1422,163,760,10176])
unseenXExpand.append([1222,263,960,16176])

In [50]:
y_pred1 = model.predict(unseenXExpand)

In [51]:
y_pred1

array([0, 1], dtype=int64)